services:
  zen-pos:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "6200:8000"
    environment:
      MONGO_URL: mongodb://mongo:i0modd8vtnbbo6jg@148.230.116.203:8765
      MONGO_DB_NAME: zenpos
      JWT_SECRET: 58153621b5fb04705489eef887f849d5cf1c6eedb591d3f92c66e17099e3ffd0
      JWT_ALGORITHM: HS256
      JWT_ACCESS_EXPIRE_MINUTES: 60
      JWT_REFRESH_EXPIRE_DAYS: 7
      APP_ENV: production
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
      CORS_ORIGINS: http://localhost:8000
      STATIC_DIR: /app/static
