version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: zenpos-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: zenpos

  api:
    build: .
    container_name: zenpos-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      MONGO_URL: mongodb://mongo:27017
    depends_on:
      - mongo
    volumes:
      - ./app:/app/app          # hot-reload in dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongo_data:
